version: '2'

services:
  kafka-cluster:
    image: lensesio/fast-data-dev:2.3.0
    container_name: fast-data-dev
    environment:
      ADV_HOST: 127.0.0.1         # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
      CONNECTORS: jdbc,cassandra
      RUN_AS_ROOT: 1
    network_mode: host
    volumes:
      - /home/henriksveen/code/kafka/kafka-beginners-course/spooldir-example/kafka-connect-spooldir:/connectors/kafka-connect-spooldir
      - /home/henriksveen/code/kafka/kafka-beginners-course/spooldir-example:/example/spooldir
      - /home/henriksveen/code/kafka/kafka-beginners-course/nobill-sink-connector/target/nobill-sink-connector-1.0-SNAPSHOT-package/share/java/nobill-sink-connector:/connectors/nobill-sink-connector
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker
